"use client";

import { useEffect, useState } from "react";
import { getCoreClient, type Event } from "@/lib/core";

export default function AlertsPage() {
  const [events, setEvents] = useState<Event[]>([]);
  const [filteredEvents, setFilteredEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [severityFilter, setSeverityFilter] = useState<string>("all");
  const [categoryFilter, setCategoryFilter] = useState<string>("all");
  const [searchQuery, setSearchQuery] = useState<string>("");

  const client = getCoreClient();

  useEffect(() => {
    loadEvents();
  }, []);

  useEffect(() => {
    filterEvents();
  }, [events, severityFilter, categoryFilter, searchQuery]);

  const loadEvents = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await client.getEvents({
        since: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        min_severity: 1,
        limit: 500,
      });
      setEvents(data.items ?? []);
    } catch (error) {
      console.error("Failed to load events:", error);
      setError("Failed to load alerts activities");
      setEvents([]);
    } finally {
      setLoading(false);
    }
  };

  const filterEvents = () => {
    let filtered = [...events];

    if (severityFilter !== "all") {
      const minSeverity = parseInt(severityFilter);
      filtered = filtered.filter((e) => e.severity >= minSeverity);
    }

    if (categoryFilter !== "all") {
      filtered = filtered.filter((e) => e.category === categoryFilter);
    }

    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(
        (e) =>
          e.summary.toLowerCase().includes(query) ||
          e.device_id?.toLowerCase().includes(query) ||
          e.category.toLowerCase().includes(query)
      );
    }

    setFilteredEvents(filtered);
  };

  const getSeverityColor = (severity: number) => {
    if (severity >= 70) return "text-red-400";
    if (severity >= 40) return "text-yellow-400";
    return "text-blue-400";
  };

  const getSeverityBadge = (severity: number) => {
    if (severity >= 70) return "bg-red-900/50 text-red-300 border-red-700";
    if (severity >= 40) return "bg-yellow-900/50 text-yellow-300 border-yellow-700";
    return "bg-blue-900/50 text-blue-300 border-blue-700";
  };

  const getCategoryIcon = (category: string) => {
    const icons: Record<string, string> = {
      network: "🌐",
      security: "🔒",
      device: "📱",
      alert: "🚨",
      system: "⚙️",
      arp: "🔍",
      risk: "⚠️",
      honeypot: "🎯",
    };
    return icons[category] || "📋";
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const categories = Array.from(new Set(events.map((e) => e.category))).sort();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-white">Alerts Activities</h1>
        <p className="text-slate-400 mt-1">All security events and alerts generated by AmmanGate</p>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="card">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">Total Events</p>
              <p className="text-2xl font-bold text-white">{events.length}</p>
            </div>
            <div className="text-3xl">📊</div>
          </div>
        </div>
        <div className="card border-l-4 border-red-500">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">Critical</p>
              <p className="text-2xl font-bold text-red-400">
                {events.filter((e) => e.severity >= 70).length}
              </p>
            </div>
            <div className="text-3xl">🔴</div>
          </div>
        </div>
        <div className="card border-l-4 border-yellow-500">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">Warnings</p>
              <p className="text-2xl font-bold text-yellow-400">
                {events.filter((e) => e.severity >= 40 && e.severity < 70).length}
              </p>
            </div>
            <div className="text-3xl">🟡</div>
          </div>
        </div>
        <div className="card border-l-4 border-blue-500">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">Info</p>
              <p className="text-2xl font-bold text-blue-400">
                {events.filter((e) => e.severity < 40).length}
              </p>
            </div>
            <div className="text-3xl">🔵</div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="card">
        <div className="flex flex-wrap gap-4">
          <input
            type="text"
            placeholder="Search events..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="input flex-1 min-w-[200px]"
          />

          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="input"
          >
            <option value="all">All Severities</option>
            <option value="70">Critical (70+)</option>
            <option value="40">Warning (40-69)</option>
            <option value="20">Notice (20-39)</option>
            <option value="1">Info (1-19)</option>
          </select>

          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="input"
          >
            <option value="all">All Categories</option>
            {categories.map((cat) => (
              <option key={cat} value={cat}>
                {cat.charAt(0).toUpperCase() + cat.slice(1)}
              </option>
            ))}
          </select>

          <button
            onClick={loadEvents}
            disabled={loading}
            className="btn btn-primary"
          >
            {loading ? "Refreshing..." : "Refresh"}
          </button>
        </div>

        <div className="mt-3 text-sm text-slate-400">
          Showing {filteredEvents.length} of {events.length} events
        </div>
      </div>

      {/* Events List */}
      {loading && events.length === 0 ? (
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        </div>
      ) : error ? (
        <div className="card bg-red-900/30 border-red-700">
          <p className="text-red-400">{error}</p>
        </div>
      ) : filteredEvents.length === 0 ? (
        <div className="card text-center py-12">
          <div className="text-6xl mb-4">📭</div>
          <p className="text-slate-400">No events found matching your filters</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredEvents.map((event) => (
            <div
              key={event.id}
              className="card hover:border-slate-600 transition-all"
            >
              <div className="flex items-start gap-4">
                <div className="text-3xl flex-shrink-0">{getCategoryIcon(event.category)}</div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <span className="inline-block px-2 py-1 text-xs font-semibold rounded-full bg-slate-700 text-slate-300 mb-2">
                        {event.category.toUpperCase()}
                      </span>
                      <h3 className="text-white font-medium">{event.summary}</h3>
                      {event.device_id && (
                        <p className="text-sm text-slate-400 mt-1">
                          Device: <span className="font-mono">{event.device_id}</span>
                        </p>
                      )}
                    </div>

                    <div className="flex flex-col items-end gap-2">
                      <span className={`px-3 py-1 text-xs font-semibold rounded-full border ${getSeverityBadge(event.severity)}`}>
                        {event.severity >= 70 ? "Critical" : event.severity >= 40 ? "Warning" : event.severity >= 20 ? "Notice" : "Info"} ({event.severity})
                      </span>
                      <span className="text-sm text-slate-400">{formatDate(event.ts)}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
